# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  project: '**/*.csproj'
  buildConfiguration: 'Release'

jobs:
- job: 'Build'
  displayName: 'Build'
  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    displayName: 'Restore NuGet'
    inputs:
      restoreSolution: '$(solution)'

  - task: UseDotNet@2
    displayName: 'Set .net Core Version'
    inputs:
      version: '2.1.x'
      packageType: runtime

  - task: DotNetCoreCLI@2
    displayName: 'Build Projects'
    inputs:
      command: build
      projects: $(project)
      configuration: '$(buildConfiguration)'